server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: cx15665090390
  redis:
    host: 8.130.64.110
    port: 6379
    password: Passw0rd
    database: 0
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis-plus:
  configuration:
    #下划线映射驼峰命名法
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      #雪花算法配置id
    banner: false
reggie:
  path: D:\JetBrains\project\reggie_take_out\src\main\resources\static\backend\images\dishImage\